// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ColorSoft.Web.Controllers {
    public partial class TemplatesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TemplatesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TemplatesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TemplatesController Actions { get { return MVC.Templates; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Templates";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Templates";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string UsersList = "UsersList";
            public readonly string ColorMatches = "ColorMatches";
            public readonly string MessagesList = "MessagesList";
            public readonly string ProductsList = "ProductsList";
            public readonly string OrganizationsList = "OrganizationsList";
            public readonly string Login = "Login";
            public readonly string Register = "Register";
            public readonly string Home = "Home";
            public readonly string About = "About";
            public readonly string Contact = "Contact";
            public readonly string Dashboard = "Dashboard";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string UsersList = "UsersList";
            public const string ColorMatches = "ColorMatches";
            public const string MessagesList = "MessagesList";
            public const string ProductsList = "ProductsList";
            public const string OrganizationsList = "OrganizationsList";
            public const string Login = "Login";
            public const string Register = "Register";
            public const string Home = "Home";
            public const string About = "About";
            public const string Contact = "Contact";
            public const string Dashboard = "Dashboard";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass {
                public readonly string _About = "_About";
                public readonly string _AddOrganization = "_AddOrganization";
                public readonly string _AddUser = "_AddUser";
                public readonly string _ColorMatchesList = "_ColorMatchesList";
                public readonly string _Contact = "_Contact";
                public readonly string _Dashboard = "_Dashboard";
                public readonly string _DeleteMessage = "_DeleteMessage";
                public readonly string _DeleteOrganization = "_DeleteOrganization";
                public readonly string _DeleteUser = "_DeleteUser";
                public readonly string _Home = "_Home";
                public readonly string _Login = "_Login";
                public readonly string _MessagesList = "_MessagesList";
                public readonly string _OrganizationsList = "_OrganizationsList";
                public readonly string _ProductsList = "_ProductsList";
                public readonly string _Register = "_Register";
                public readonly string _UsersList = "_UsersList";
            }
            public readonly string _About = "~/Views/Templates/_About.cshtml";
            public readonly string _AddOrganization = "~/Views/Templates/_AddOrganization.cshtml";
            public readonly string _AddUser = "~/Views/Templates/_AddUser.cshtml";
            public readonly string _ColorMatchesList = "~/Views/Templates/_ColorMatchesList.cshtml";
            public readonly string _Contact = "~/Views/Templates/_Contact.cshtml";
            public readonly string _Dashboard = "~/Views/Templates/_Dashboard.cshtml";
            public readonly string _DeleteMessage = "~/Views/Templates/_DeleteMessage.cshtml";
            public readonly string _DeleteOrganization = "~/Views/Templates/_DeleteOrganization.cshtml";
            public readonly string _DeleteUser = "~/Views/Templates/_DeleteUser.cshtml";
            public readonly string _Home = "~/Views/Templates/_Home.cshtml";
            public readonly string _Login = "~/Views/Templates/_Login.cshtml";
            public readonly string _MessagesList = "~/Views/Templates/_MessagesList.cshtml";
            public readonly string _OrganizationsList = "~/Views/Templates/_OrganizationsList.cshtml";
            public readonly string _ProductsList = "~/Views/Templates/_ProductsList.cshtml";
            public readonly string _Register = "~/Views/Templates/_Register.cshtml";
            public readonly string _UsersList = "~/Views/Templates/_UsersList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TemplatesController: ColorSoft.Web.Controllers.TemplatesController {
        public T4MVC_TemplatesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult UsersList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UsersList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ColorMatches() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ColorMatches);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MessagesList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MessagesList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ProductsList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ProductsList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult OrganizationsList() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.OrganizationsList);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Login() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Login);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Home() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Home);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult About() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.About);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Contact() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Contact);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Dashboard() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Dashboard);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
